### ISSUE TITLE
Managed account has already been registered

### ISSUE THREAD

**Issue by tsk4600** [brianlala/AutoSPInstaller#23]
Hi,
the script stalls at:

- Registering managed account tskr.local\s_GORtest_ca_apppool...
New-SPManagedAccount : Account DOMAIN\ca_apppool has already been registered.
At C:\SP\AutoSPInstaller\AutoSPInstallerFunctions.ps1:2236 char:17
+                 New-SPManagedAccount -Credential $credAccount | Out-N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...wManagedAccount:SPCmdletNewManagedA
   ccount) [New-SPManagedAccount], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewManagedAccount

--------------------------------------------------------------
 - Script halted!

Exception             : System.Management.Automation.RuntimeException:    - Failed to create manag
                        ed account
TargetObject          :    - Failed to create managed account
CategoryInfo          : OperationStopped: (   - Failed to create managed account:String) [], Runti
                        meException
FullyQualifiedErrorId :    - Failed to create managed account
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at AddManagedAccounts, C:\SP\AutoSPInstaller\AutoSPInstallerFunctions.ps1:
                         line 2237
                        at Setup-Farm, C:\SP\AutoSPInstaller\AutoSPInstallerMain.ps1: line 212
                        at <ScriptBlock>, C:\SP\AutoSPInstaller\AutoSPInstallerMain.ps1: line 427
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

any ideas?

regards Theis

**Comment by brianlala** [comment]
Is your account name create than 20 characters?

**Comment by sduschinger** [comment]
I had the same problem. There was a problem and I re-ran AutoSPInstaller and i ran into this error.


Open the SharePoint Shell and run Get-SPManagedAccount. Make sure that in your config-file the username is exactly as stated there. In my case i had to remote ".local" from the domain name.

**Comment by farid-ics** [comment]
hello, 

i had same issue. 

the solution is simple:
you must remove the extension from your domain
example: 
mydomain.net change it to mydomain
or :
mydomain.net in capitals MYDOMAINENET
