### ISSUE TITLE
Issue installing SharePoint 2016 on single server Farm using MinRole

### ISSUE THREAD

**Issue by rishiuiit** [brianlala/AutoSPInstaller#28]
I am facing issue with installing SharePoint 2016 on a single server farm. I created configuration XML and trying to install, but its prompting for Key. The key is already specified in the config file. Am I doing anything wrong?

**Comment by brianlala** [comment]
Sorry, this isn't a support forum, it's a place to report suspected issues with AutoSPInstaller. However I would first verify that you don't have any other XML config files in the same location that may contain blank product keys - the script might be picking them up by accident.
