### ISSUE TITLE
Key cannot be null

### ISSUE THREAD

**Issue by jcollinsks** [brianlala/AutoSPInstaller#46]
**SharePoint 2019 Min Role**
I'm trying to setup a farm, and getting the following error:
![image](https://user-images.githubusercontent.com/2774588/65072371-9d81a180-d945-11e9-9541-f953002dbebf.png)

I've tried setting the version to "16" and setting the year manually to "2019" as well as tried changing the state service to false when provisioning.

**Comment by jcollinsks** [comment]
@brianlala any idea on this one?

**Comment by jcollinsks** [comment]
For anyone having the same issue, the fix is to remove $spVer = $spVersions.$spYear and set $spVer = "16" or the version you're installing
![image](https://user-images.githubusercontent.com/2774588/65075764-619e0a80-d94c-11e9-9ba1-97c1402db258.png)

**Comment by brianlala** [comment]
Hard-coding the version isn't really a fix :) we have to figure out why exactly this is happening for you... this is fairly old code and has worked for a while.

**Comment by jcollinsks** [comment]
I agree, I saw someone else on the website had the same error in the discussion area. Is there anything you'd like to see to make sure it's setup correctly, I can strip passwords from the input file and upload it.
