### ISSUE TITLE
Failing to create site collection

### ISSUE THREAD

**Issue by ekramyelnaggar** [brianlala/AutoSPInstaller#58]
The script is working fine till it reaches the point to create a site collection inside the portal web application , with the following error : 

Exception             : System.UnauthorizedAccessException:
                        <nativehr>0x80070005</nativehr><nativestack></nativestack>Access denied.
                           at
                        Microsoft.SharePoint.SPGlobal.HandleUnauthorizedAccessException(UnauthorizedAccessException ex)
                           at Microsoft.SharePoint.Library.SPRequest.CreateSite(Guid gApplicationId, String bstrUrl,
                        Int32 lZone, Guid gSiteId, Guid gDatabaseId, Guid gSiteSubscriptionId, String
                        bstrDatabaseServer, String bstrDatabaseName, String bstrDatabaseUsername, String
                        bstrDatabasePassword, String bstrTitle, String bstrDescription, UInt32 nLCID, String
                        bstrOwnerLogin, String bstrOwnerUserKey, String bstrOwnerName, String bstrOwnerEmail, String
                        bstrSecondaryContactLogin, String bstrSecondaryContactUserKey, String
                        bstrSecondaryContactName, String bstrSecondaryContactEmail, Boolean bADAccountMode, Boolean
                        bHostHeaderIsSiteName, Int32 iDatabaseVersionMajor, Int32 iDatabaseVersionMinor, Int32
                        iDatabaseVersionBuild, Int32 iDatabaseVersionRevision, Int32 iSprocsVersionMajor, Int32
                        iSprocsVersionMinor, Int32 iSprocsVersionBuild, Int32 iSprocsVersionRevision, String
                        bstrSiteSchemaVersion, Boolean bCreateFromMaster, String bstrDenyPermMaskGroupId)
                           at
                        Microsoft.SharePoint.Administration.SPSiteCollection.AddInternal(SPSiteCollectionAddParameters
                        param)
                           at Microsoft.SharePoint.Administration.SPSiteCollection.Add(SPSiteCollectionAddParameters
                        param)
                           at Microsoft.SharePoint.PowerShell.SPCmdletNewSite.CreateDataObject()
                           at Microsoft.SharePoint.PowerShell.SPNewCmdletBase`1.InternalProcessRecord()
                           at Microsoft.SharePoint.PowerShell.SPCmdlet.ProcessRecord()
TargetObject          : Microsoft.SharePoint.PowerShell.SPCmdletNewSite
CategoryInfo          : InvalidData: (Microsoft.Share...SPCmdletNewSite:SPCmdletNewSite) [New-SPSite],
                        UnauthorizedAccessException
FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSite
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at CreateWebApp, D:\install\SP\AutoSPInstaller\Automation\AutoSPInstallerModule.psm1: line 2997
                        at CreateWebApplications, D:\install\SP\AutoSPInstaller\Automation\AutoSPInstallerModule.psm1:
                        line 2763
                        at Set-FarmConfig, D:\install\SP\AutoSPInstaller\Automation\AutoSPInstallerMain.ps1: line 239
                        at <ScriptBlock>, D:\install\SP\AutoSPInstaller\Automation\AutoSPInstallerMain.ps1: line 438
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by brianlala** [comment]
Known issue, see https://github.com/brianlala/AutoSPInstaller/issues/17
