### ISSUE TITLE
webapplication provision on WFE

### ISSUE THREAD

**Issue by hr-crd** [brianlala/AutoSPInstaller#67]
is there anyway can **autospinstaller** restrict webapplication provision on **ONLY Web Front End servers** for SP2019? I saw that sites are provisioned on APP servers too :(. There is no provision tag for <WebApplication />... it was there in 2013 desktop version

**Comment by brianlala** [comment]
This actually isn't an AutoSPInstaller thing, this is SharePoint 2016+ thing. MinRole determines which servers will have the Foundation Web Application service provisioned and this in turn controls which servers get the web apps provisioned on them. And Application Server and Application Server with Search MinRoles both have that service provisioned by default.

**Comment by hr-crd** [comment]
Thank you for clarification
