### ISSUE TITLE
Function ConfigureDistributedCacheService adds wrong managed account

### ISSUE THREAD

**Issue by aaronhamilton** [brianlala/AutoSPInstaller#70]
I noticed my DCache was being assigned a different service account than I intended... and I think this is why...

![2020-10-09_23-47-44](https://user-images.githubusercontent.com/22530324/95645147-4be51100-0a8a-11eb-9bcd-a7909703108d.png)

**Comment by brianlala** [comment]
Not sure why you'd want or need to run it as any other account, but of course you're welcome to use your own mods here! Are you just making a note of this or are you requesting a modification to the shared codebase?

**Comment by aaronhamilton** [comment]
Hi Brian!
I think I'm suggesting a change to the shared codebase. Since the XML config file has a specific property for **spDCache** service account, doesn't it make sense that the function honor it? 
Thanks
Aaron

**Comment by brianlala** [comment]
Wait, where does the XML have a specific property for spDCache account...?

**Comment by aaronhamilton** [comment]
Good question....... checking..... okay so this is what happened. 

I was given a list of service accounts for my new farm (as specified by a consultant). DCache was on the list of accounts. So I created a managed account in the AutoSP config called `spDCache`. Then I _assumed_ AutoSPInstaller would ... *ahem* ... magically figure out my intention and use it when provisioning distributed cache. 

_mea culpa!!!_ ... I'm sorry for wasting your time.... and the learning continues...

**Comment by brianlala** [comment]
Hehe no worries. Had me second guessing there!
