### ISSUE TITLE
AutoSPInstaller: Error: Custom file location is not accessible

### ISSUE THREAD

**Issue by danone1985** [brianlala/AutoSPInstaller#71]
hello,

I'm installing a SharePoint 2016 in automated way using autospinstaller.

Scripts is blocked with the following error, all  the time (from what I understand, something related to a prerquisite missing or not found).

Does anyone have any idea ?

**********************
Windows PowerShell transcript start
Start time: 20201112092651
Username: CONTOSO\admin
RunAs User: CONTOSO\admin
Machine: APP (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoExit -ExecutionPolicy Bypass C:\SP\Automation\\AutoSPInstallerMain.ps1 C:\SP\Automation\\AutoSPInstallerInput-APP.xml
Process ID: 3868
**********************
Transcript started, output file is C:\Users\admin.CONTOSO\Desktop\AutoSPInstaller-2020-11-12_9-26.log
-----------------------------------
| Automated SP2016 install script |
| Started on: 11/12/2020 9:26:51 AM |
-----------------------------------
 - SharePoint 2016 binaries are not yet installed.
 - Install based on: 
  - C:\SP\Automation\\AutoSPInstallerInput-APP.xml 
  - Environment: SP2016 
  - Version: 3.99.70
--------------------------------------------------------------
 - Validating user accounts and passwords...
 - Account "CONTOSO\spfarm" (Account)...
Verified.
 - Account "CONTOSO\spsvc" (ManagedAccount)...
Verified.
 - Account "CONTOSO\spapppool" (ManagedAccount)...
Verified.
 - Account "CONTOSO\spuserprofile" (ManagedAccount)...
Verified.
 - Account "CONTOSO\spsearch" (ManagedAccount)...
Verified.
 - Account "CONTOSO\spsearch" (Search Service Application)...
Verified.
 - Account "CONTOSO\SPSuperReader"...
Verified.
 - Account "CONTOSO\SPSuperUser"...
Verified.
--------------------------------------------------------------
 - Writing AutoSPInstaller.xml to C:\Users\admin.CONTOSO\AppData\Local\Temp...
--------------------------------------------------------------
 - Testing access to SQL server/instance/alias: SQL.contoso.local
  - Trying to connect to 'SQL.contoso.local'
  - Using connection string 'Server=SQL.contoso.local;Integrated Security=SSPI;'...
Success
  - SQL Server version is: 15.0.4073.23
  - This instance of SQL Server is not clustered
  - Check if CONTOSO\admin has dbcreator server role...
Passed
  - Check if CONTOSO\admin has securityadmin server role...
Passed
--------------------------------------------------------------
--------------------------------------------------------------
 - Disabling Loopback Check...
--------------------------------------------------------------
--------------------------------------------------------------
 - Disabling IE Enhanced Security...
--------------------------------------------------------------
--------------------------------------------------------------
 - Setting services Spooler, AudioSrv and TabletInputService to Manual...
 - Spooler is already stopped and set Manual, no action required.
 - AudioSrv is already stopped and set Manual, no action required.
 - TabletInputService is already stopped and set Manual, no action required.
 - Setting unused services WerSvc to Disabled...
 - WerSvc is already stopped and disabled, no action required.
 - Finished disabling services.
--------------------------------------------------------------
--------------------------------------------------------------
 - Disabling Certificate Revocation List (CRL) check...
  - Registry...
  - Machine.config files...
   - v2.0.50727...
OK.
   - v4.0.30319...
OK.
 - Done.
--------------------------------------------------------------
--------------------------------------------------------------
 - Installing Prerequisite Software:
  - .Net Framework 3.5.1 from "C:\SP\2016\SharePoint\PrerequisiteInstallerFiles\sxs"...
Already installed.
  - Running Prerequisite Installer (offline mode)...
.
Done.
  - Prerequisite Installer completed in 00:00:05.
WARNING: 2020-11-12 09:27:00 - Error: Custom file location is not accessible

PS>TerminatingError(Write-Warning): "Cannot bind argument to parameter 'Message' because it is null."
>> TerminatingError(Write-Warning): "Cannot bind argument to parameter 'Message' because it is null."
>> TerminatingError(Write-Warning): "Cannot bind argument to parameter 'Message' because it is null."
--------------------------------------------------------------
 - Script halted!

Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to
                        parameter 'Message' because it is null.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Write-Warning], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteWarningComman
                        d
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at InstallPrerequisites, C:\SP\Automation\AutoSPInstallerModule.psm1: line 911
                        at Start-Install, C:\SP\Automation\AutoSPInstallerMain.ps1: line 195
                        at <ScriptBlock>, C:\SP\Automation\AutoSPInstallerMain.ps1: line 409
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

-----------------------------------
| Automated SP2016 install script |
| Started on: 11/12/2020 9:26:51 AM |
| Aborted:    11/12/2020 9:27:05 AM |
-----------------------------------

PS C:\SP\Automation> 0
0

thank you.

**Comment by brianlala** [comment]
Could this be related to [this](https://github.com/brianlala/AutoSPSourceBuilder/issues/76)?

**Comment by danone1985** [comment]
> Could this be related to [this](https://github.com/brianlala/AutoSPSourceBuilder/issues/76)?

not sure, prerequisites seem to be complete. 
If i do an online install, it passes without problems

![image](https://user-images.githubusercontent.com/23168113/98955998-d55f8700-24ff-11eb-897e-be0f0941ab6b.png)

**Comment by erichager** [comment]
@brianlala I'm having the exact same issue. Prerequisites are complete. Servers don't have internet access so I had to do an offline install of the prereqs but the autospinstaller log file shows that it passes the prereq install and then fails with the same error @danone1985 is reporting. Was a solution ever found for this issue?

Thanks,
Eric

**Comment by trevevs** [comment]
also getting this error installing 2013 onto 2012R2.  I wonder if autoSP was ever tested fully for offline installation?  It needs to be fixed.  This was helpful https://azurecloudai.blog/2012/12/26/install-and-download-sharepoint-2013-prerequisites-offline-manually/  Make sure you download all needed file into the 2013\SharePoint\PrerequisiteInstallerFiles\ folder.
The script should really check for the presence of prereq files, it needs better error trapping.

Even when all files are present, the prereq tool still trying to download them...

WARNING: 2021-03-25 08:15:50 - Error: This file does not exist
WARNING: 2021-03-25 08:16:39 - Error: InternetOpenUrl failed (0X80072EFD=-2147012867)
WARNING: 2021-03-25 08:16:39 - Error: Download failed (0)
WARNING: 2021-03-25 08:16:39 - Error: The tool was unable to download Microsoft Sync Framework Runtime v1.0 SP1 (x64).
Please check your Internet connection and try again.
WARNING: 2021-03-25 08:20:09 - Error: InternetOpenUrl failed (0X80072EFD=-2147012867)
WARNING: 2021-03-25 08:20:09 - Error: Download failed (0)
WARNING: 2021-03-25 08:20:09 - Error: The tool was unable to download Windows Server AppFabric. Please check your
Internet connection and try again.
WARNING: 2021-03-25 08:20:09 - Last return code (-1)

**Comment by trevevs** [comment]
also had hellish time installing MicrosoftIdentityExtensions-64.. turns out my VM only had 2 CPUs- bumped it up to 4 CPUs and it suddenly started working- had to install all pre-reqs manually.  This AutoSP script needs fixing :-)

**Comment by AstrProp** [comment]
> также пришлось адское время на установку MicrosoftIdentityExtensions-64.. Оказывается, у моей виртуальной машины было только 2 процессора - доработал до 4 процессоров, и он внезапно начал работать - пришлось устанавливать все предварительные инструкции вручную. Этот скрипт AutoSP нуждается в исправлении :-)

У меня 4 ядра и это не помогло ( установка Identity в ручную тоже не помогла.

**Comment by oshit** [comment]
I found out Prerequisite Installer is looking for the file WcfDataServices.exe, so I rename the WcfDataServices56.exe to WcfDataServices.exe

**Comment by brianlala** [comment]
If you use [AutoSPSourceBuilder ](https://github.com/brianlala/AutoSPSourceBuilder)to prep your source and prereqs it should help avoid all of this.

**Comment by DiHendriks** [comment]
This case is closed but it is not the solution. Building it with the AutoSPSourceBuilder is not the solution and the same error occurs. Even the version is not update ..

**Comment by brianlala** [comment]
If you're looking for community help for this fairly old problem it would be good to provide more information.
