### ISSUE TITLE
AutoSPInstaller Error - Null argument for DelegateComputer

### ISSUE THREAD

**Issue by laromeo** [brianlala/AutoSPInstaller#73]
I'm trying to build a small 2 server farm and this is the error that I am getting. It is not adding the second server to the 'DelegatComupter' variable? Any suggestions would be helpful.

Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoExit -ExecutionPolicy Bypass C:\Windows\ProPatches\Installation\AutoSPInstaller-master\SP\Automation\\AutoSPInstallerMain.ps1 C:\Windows\ProPatches\Installation\AutoSPInstaller-master\SP\Automation\\AutoSPInstallerInput.xml
Process ID: 7448
PSVersion: 5.1.14393.3866
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.3866
BuildVersion: 10.0.14393.3866
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\svc_spadmins\Desktop\AutoSPInstaller-2020-11-17_8-52.log
-----------------------------------
| Automated SP2016 install script |
| Started on: 11/16/2020 11:08:16 PM |
-----------------------------------
-----------------------------------
| Automated SP2016 Remote Installs |
| Started on: 11/16/2020 11:08:16 PM |
-----------------------------------
PS>TerminatingError(Enable-WSManCredSSP): "Cannot validate argument on parameter 'DelegateComputer'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."
Enable-WSManCredSSP : Cannot validate argument on parameter 'DelegateComputer'. The argument is null or empty. Provide 
an argument that is not null or empty, and then try the command again.
At C:\Windows\ProPatches\Installation\AutoSPInstaller-master\SP\Automation\AutoSPInstallerModule.psm1:6930 char:63
+ ... dSSP -Role Client -Force -DelegateComputer $remoteFarmServers | Out-N ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Enable-WSManCredSSP], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WSMan.Management.EnableWSManCredSSPCommand
Enable-WSManCredSSP : Cannot validate argument on parameter 'DelegateComputer'. The argument is null or empty. Provide
an argument that is not null or empty, and then try the command again.
At C:\Windows\ProPatches\Installation\AutoSPInstaller-master\SP\Automation\AutoSPInstallerModule.psm1:6930 char:63
+ ... dSSP -Role Client -Force -DelegateComputer $remoteFarmServers | Out-N ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Enable-WSManCredSSP], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WSMan.Management.EnableWSManCredSSPCommand

Press any key to exit...

**Comment by brianlala** [comment]
Please validate your XML over at https://autospinstaller.com. Closing this as it is not an issue but rather probably just a typo in your XML.

If you still don't have any luck try just kicking the script off on both servers instead of using the remote functionality.

Brian
