### ISSUE TITLE
Integrate with new SSL certificate management functionality in SPSE

### ISSUE THREAD

**Issue by TroyStarr** [brianlala/AutoSPInstaller#80]
You may want to consider having AutoSPInstaller integrate with the new [SSL certificate management](https://docs.microsoft.com/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-subscription-edition#sslcm) functionality in SharePoint Server Subscription Edition.  (The `AssignCert` function in AutoSPInstaller and related code.)  There's a risk that SharePoint Server Subscription Edition might stomp on the SSL certificate binding configured by the existing AutoSPInstaller code now that SharePoint thinks it has control over the SSL certificate used by the SSL binding.

Take a look at the following new SharePoint PowerShell cmdlets to see what functionality is available:

- [Export-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/export-spcertificate?view=sharepoint-server-ps): Exports certificates from the SharePoint farm.
- [Get-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/get-spcertificate?view=sharepoint-server-ps): Returns all certificates that match the specified criteria.
- [Import-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/import-spcertificate?view=sharepoint-server-ps): Imports certificates into the SharePoint farm.
- [Move-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/move-spcertificate?view=sharepoint-server-ps): Moves the specified certificate to a different certificate store.
- [New-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/new-spcertificate?view=sharepoint-server-ps): Creates a new certificate signing request. (Also creates a self-signed certificate that's placed in SharePoint's Pending certificate store.)
- [Remove-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/remove-spcertificate?view=sharepoint-server-ps): Deletes a certificate and any associated private key.
- [Rename-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/rename-spcertificate?view=sharepoint-server-ps): Changes the friendly name (display name) of a certificate.
- [Renew-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/renew-spcertificate?view=sharepoint-server-ps): Renews a certificate and creates a new certificate signing request.
- [Switch-SPCertificate](https://docs.microsoft.com/powershell/module/sharepoint-server/switch-spcertificate?view=sharepoint-server-ps): Replaces existing certificate assignments with a new certificate.
- [Get-SPCertificateSettings](https://docs.microsoft.com/powershell/module/sharepoint-server/get-spcertificatesettings?view=sharepoint-server-ps): Returns the default properties for creating and renewing certificates and the certificate health analyzer rules.
- [Set-SPCertificateSettings](https://docs.microsoft.com/powershell/module/sharepoint-server/set-spcertificatesettings?view=sharepoint-server-ps): Configures certificate management settings.
- [Add-SPCertificateNotificationContact](https://docs.microsoft.com/powershell/module/sharepoint-server/add-spcertificatenotificationcontact?view=sharepoint-server-ps): Adds an email address to the list of contacts to be notified when certificates are about to expire or have already expired.
- [Clear-SPCertificateNotificationContact](https://docs.microsoft.com/powershell/module/sharepoint-server/clear-spcertificatenotificationcontact?view=sharepoint-server-ps): Deletes all email addresses from the list of contacts to be notified when certificates are about to expire or have already expired.
- [Get-SPCertificateNotificationContact](https://docs.microsoft.com/powershell/module/sharepoint-server/get-spcertificatenotificationcontact?view=sharepoint-server-ps): Gets the email addresses to be notified when certificates are about to expire or have already expired.
- [Remove-SPCertificateNotificationContact](https://docs.microsoft.com/powershell/module/sharepoint-server/remove-spcertificatenotificationcontact?view=sharepoint-server-ps): Deletes an email address from the list of contacts to be notified when certificates are about to expire or have already expired.

... and the various PowerShell cmdlets that have been updated to add a `-Certificate <SPServerCertificatePipeBind>` parameter to specify which SSL certificate managed by the SharePoint SSL certificate management feature should be used.  That includes New-SPCentralAdministration, Set-SPCentralAdministration, New-SPWebApplication, Set-SPWebApplication, and New-SPWebApplicationExtension.

**Comment by brianlala** [comment]
Definitely! Yesterday's push was just about providing initial SE support; I'll look at integrating the new cmdlets ASAP. 

I also plan on looking at how SharePointDSC can leverage the new cert management too - if Yorick isn't already on it.

Cheers
