### ISSUE TITLE
AutoSPInstallerOnline

### ISSUE THREAD

**Issue by NoralK** [brianlala/AutoSPInstaller#86]
Hi Brian,

Do you know if Ivan is going to update his project, there is a request I made in early Nov and he has not responded.  Since you are also listed in the contact page I thought I would ping you.

Cheers

**Comment by brianlala** [comment]
Closing this as it is not really an issue and not strictly related to AutoSPInstaller itself. I will reach out to Ivan though and ask if he plans on updating the website for SharePoint Subscription Edition.
