### ISSUE TITLE
Set-SPAppSiteSubscriptionName : "App Site Subscription" contains invalid character ' '.

### ISSUE THREAD

**Issue by jonimattila** [brianlala/AutoSPInstaller#9]
I got this error, to fix this error do not have spaces in App Site Subscription name, so name it AppSiteSubscription.

Error:
Set-SPAppSiteSubscriptionName : "App Site Subscription" contains invalid character ' '.
At C:\SP\AutoSPInstaller\AutoSPInstallerFunctions.ps1:6013 char:9
+         Set-SPAppSiteSubscriptionName -Name $serviceConfig.AppSiteSub ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...ubscriptionName:SetSPAppSiteSubscriptionName) [Set-SPApp
   SiteSubscriptionName], SPException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Administration.SPAppCmdlets.SetSPAppSiteSubscriptionName

**Comment by brianlala** [comment]
Right, easy fix. I'll just add double-quotes around it so spaces will work.

Brian
