### ISSUE TITLE
Has AutoSPInstaller development ceased?

### ISSUE THREAD

**Issue by cloudgreen** [brianlala/AutoSPInstaller#94]
@brianlala Has the development of the world's best SharePoint Server installation tool ceased? Or has it maybe reached "perfection" and thanks to the evergreen Subscription Edition does not necessitate any further development?

Thank you for your fantastic work during the years! 💚

**Comment by brianlala** [comment]
Essentially, yes :|  

...Except the world's best SP installation tool is now [SharePointDSC ](https://github.com/dsccommunity/SharePointDsc) (and it has been for a while). I myself have been using that almost exclusively lately. Check it out!

My job role has shifted to be primarily cloud-focused (SPO etc.) Plus the last major changes to AutoSPInstaller were indeed focused around Subscription Edition, and where necessary I might make minor fixes here and there to ensure it continues to remain compatible, but other than that I don't plan any more major enhancements.

**Comment by cloudgreen** [comment]
Thanks for your reply, Brian!

Oh, SharePointDSC sounds very interesting, thanks for the pointer. 😊I can't believe I haven't run into it until now!

When it comes to the installation of SharePoint, can you do everything with SharePointDSC that you can do with AutoSPInstaller?

I'm glad you still plan on implementing smaller fixes to keep AutoSPInstaller compatible, I suspect there could be a lot of people having dependencies on it. At least for some time, until the successor has gained more usage.

But I gotta say, you (and the community around) had a really good run with AutoSPInstaller! 👏😃

**Comment by brianlala** [comment]
Yes SharePointDSC essentially has feature parity with AutoSPInstaller (plus more). It's also more modular and extensible by design.

Cheers

**Comment by cloudgreen** [comment]
Sounds great, will look into DSC and thank you for all your hard work. It has helped a lot, during the years! 😀👍
